Update Jenkinsfile

diff --git a/python_flask_cicd/jenkins/Jenkinsfile b/python_flask_cicd/jenkins/Jenkinsfile
--- a/python_flask_cicd/jenkins/Jenkinsfile
+++ b/python_flask_cicd/jenkins/Jenkinsfile
@@ -1,23 +1,25 @@
 pipeline {
     agent any
     environment {
-        IMAGE_NAME = "flaskimage" 
-        APP_PORT = 5000
+        IMAGE_NAME = "flaskimage"  // Docker image name
+        APP_PORT = 5000  // Flask app port
     }
     stages {
         stage('checkoutscm') {
-            steps {
-                script {
-                    echo "Code checkout begin shortly.."
-                    sh '''
-                    git clone https://github.com/thangacodes/python-scripts.git
-                    cd python-scripts/python_flask_cicd
-                    echo "List out the files"
-                    ls -l .
-                    '''
-                }
+        steps {
+            script {
+                echo "Code checkout begin shortly.."
+                sh '''
+                git clone https://github.com/thangacodes/python-scripts.git || { echo 'Git clone failed'; exit 1; }
+                cd python-scripts/python_flask_cicd || { echo 'Failed to navigate to directory'; exit 1; }
+                echo "List out the files"
+                ls -l .
+                '''
             }
         }
+    }
+        }
+
         stage('build') {
             steps {
                 script {
@@ -30,6 +32,7 @@ pipeline {
                 }
             }
         }
+
         stage('unit_test') {
             steps {
                 script {
@@ -41,6 +44,7 @@ pipeline {
                 }
             }
         }
+
         stage('deploy_app') {
             steps {
                 script {
@@ -52,6 +56,7 @@ pipeline {
                 }
             }
         }
+
         stage('cleanws') {
             steps {
                 script {
@@ -61,12 +66,13 @@ pipeline {
             }
         }
     }
+
     post {
         always {
             echo "Cleaning up Docker containers..."
             sh '''
             docker ps -q | xargs docker stop || true
-            docker ps -a -q | xargs docker rm || true
+            docker ps -a -q | xargs docker rm || trued
             '''
         }
     }
